### ISSUE TITLE
4.0.0: libnl_3.2.24 doesn't build

### ISSUE THREAD

**Issue by mikaelj** [oe-lite/base#44]
Straight outta base-4.0.0:

    Preparing machine:libnl_3.2.24:do_patch
    buildhash='1dc049c026221dfef64e3a9259f0ec6b'
    Running 1 / 63 machine:libnl_3.2.24:do_patch
    > quilt -v --quiltrc /data/sabre/oelite/tlabos/tmp/work/machine/arm-cortexa9sfpt-linux-gnueabi/libnl-3.2.24/src/patches/quiltrc push
    Applying patch fix-pc-file.patch
    can't find file to patch at input line 3
    Perhaps you used the wrong -p or --strip option?
    The text leading up to this was:
    --------------------------
    |--- libnl-3.2.7/libnl-3.0.pc.in.orig   2012-02-14 10:14:31.033464884 +0100
    |+++ libnl-3.2.7/libnl-3.0.pc.in        2012-02-14 10:15:14.655707202 +0100
    --------------------------
    No file to patch.  Skipping patch.
    1 out of 1 hunk ignored
    Patch fix-pc-file.patch does not apply (enforce with -f)
    Error: Command failed: 'quilt -v --quiltrc /data/sabre/oelite/tlabos/tmp/work/machine/arm-cortexa9sfpt-linux-gnueabi/libnl-3.2.24/src/patches/quiltrc push': 1
    ERROR: machine:libnl_3.2.24:do_patch failed

Release untested?

**Comment by mikaelj** [comment]
As kimrhh was saying.... Upgrade from 3.5 to 4.0 is best done by wiping everything.

**Comment by esben** [comment]
Everything, as entire parse cache?  What else might be causing trouble?

**Comment by mikaelj** [comment]
I apparently had old recipes lying around, so nevermind this ticket.
